export const TOOL_DEFINITIONS = [
  // Operations tools
  { type: 'function', function: { name: "open_gate", description: "Open a stadium gate for fan entry/exit", parameters: { type: "object", properties: { gate_id: { type: "string", description: "'A'|'B'|'C'|'D'|'E'|'F'" } }, required: ["gate_id"] } } },
  { type: 'function', function: { name: "close_gate", description: "Close a stadium gate", parameters: { type: "object", properties: { gate_id: { type: "string" } }, required: ["gate_id"] } } },
  { type: 'function', function: { name: "adjust_gate_lanes", description: "Change number of active security lanes at a gate", parameters: { type: "object", properties: { gate_id: { type: "string" }, lanes: { type: "number", description: "1-4" } }, required: ["gate_id", "lanes"] } } },
  { type: 'function', function: { name: "reroute_gate", description: "Reroute a percentage of fans from one gate to another to balance queues", parameters: { type: "object", properties: { from_gate: { type: "string" }, to_gate: { type: "string" }, percentage: { type: "number", description: "1-100" } }, required: ["from_gate", "to_gate", "percentage"] } } },
  { type: 'function', function: { name: "dispatch_security", description: "Deploy a security team to a location", parameters: { type: "object", properties: { team_id: { type: "string" }, location: { type: "string" }, reason: { type: "string" } }, required: ["team_id", "location", "reason"] } } },
  { type: 'function', function: { name: "dispatch_medical", description: "Send a medical team to an incident location", parameters: { type: "object", properties: { team_id: { type: "string" }, location: { type: "string" }, incident_type: { type: "string" } }, required: ["team_id", "location", "incident_type"] } } },
  { type: 'function', function: { name: "dispatch_cleaning", description: "Assign a cleaning crew to a zone", parameters: { type: "object", properties: { crew_id: { type: "string" }, location: { type: "string" }, priority: { type: "string", description: "'low'|'medium'|'high'" } }, required: ["crew_id", "location", "priority"] } } },
  { type: 'function', function: { name: "send_announcement", description: "Broadcast a public address announcement to specified zones", parameters: { type: "object", properties: { message: { type: "string" }, zones: { type: "array", items: { type: "string" }, description: "zone IDs or 'all'" } }, required: ["message", "zones"] } } },
  { type: 'function', function: { name: "update_signage", description: "Change digital wayfinding signs to display a message", parameters: { type: "object", properties: { sign_ids: { type: "array", items: { type: "string" } }, message: { type: "string" } }, required: ["sign_ids", "message"] } } },
  { type: 'function', function: { name: "create_maintenance_ticket", description: "Log an equipment failure or maintenance request", parameters: { type: "object", properties: { equipment: { type: "string" }, location: { type: "string" }, priority: { type: "string" } }, required: ["equipment", "location", "priority"] } } },
  { type: 'function', function: { name: "reserve_emergency_route", description: "Clear and reserve a path for emergency vehicle access", parameters: { type: "object", properties: { from: { type: "string" }, to: { type: "string" } }, required: ["from", "to"] } } },
  
  // Information retrieval tools
  { type: 'function', function: { name: "get_zone_density", description: "Get current crowd density for a zone", parameters: { type: "object", properties: { zone_id: { type: "string" } }, required: ["zone_id"] } } },
  { type: 'function', function: { name: "get_gate_status", description: "Get queue, throughput, wait time for one or all gates", parameters: { type: "object", properties: { gate_id: { type: "string", description: "optional, omit for all" } }, required: [] } } },
  { type: 'function', function: { name: "get_team_status", description: "Get availability and location of all teams in a department", parameters: { type: "object", properties: { department: { type: "string", description: "'security'|'medical'|'cleaning'|'maintenance'" } }, required: ["department"] } } },
  { type: 'function', function: { name: "get_active_incidents", description: "Get list of unresolved incidents, optionally filtered", parameters: { type: "object", properties: { severity: { type: "string" }, type: { type: "string" } }, required: [] } } },
  { type: 'function', function: { name: "get_weather", description: "Get current weather conditions affecting the stadium", parameters: { type: "object", properties: {}, required: [] } } },
  { type: 'function', function: { name: "get_transport_status", description: "Get train/bus arrivals, delays, and incoming passenger counts", parameters: { type: "object", properties: {}, required: [] } } },
  { type: 'function', function: { name: "query_sop", description: "Search the stadium Standard Operating Procedures handbook", parameters: { type: "object", properties: { topic: { type: "string" } }, required: ["topic"] } } },
  
  // Reporting tools
  { type: 'function', function: { name: "generate_situation_summary", description: "Produce a natural language briefing of current stadium status", parameters: { type: "object", properties: {}, required: [] } } },
  { type: 'function', function: { name: "generate_shift_handover", description: "Create a structured shift handover report", parameters: { type: "object", properties: {}, required: [] } } },
  { type: 'function', function: { name: "generate_incident_report", description: "Build a report for a specific incident", parameters: { type: "object", properties: { incident_id: { type: "string" } }, required: ["incident_id"] } } }
];
